version: "3.8"

services:
    app:
        build: .
        container_name: laravel-app
        volumes:
            - .:/var/www
        networks:
            - laravel-network

    web:
        image: nginx:alpine
        container_name: laravel-web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    db:
        image: postgres:15
        container_name: laravel-db
        restart: always
        environment:
            POSTGRES_DB: sale_management_db
            POSTGRES_USER: doadmin
            POSTGRES_PASSWORD: AVNS_mtET5WtDeA_QhkKTpR_
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "25060:25060"
        networks:
            - laravel-network

volumes:
    pgdata:

networks:
    laravel-network:
        driver: bridge
